zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  routes:
    EurekaServer:
      path: /server/**
      url: http://localhost:8791
    OnlineWallet:
      path: /client/**
      serviceId: OnlineWallet

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8791/eureka
  instance:
    hostname: localhost

server:
  port: 8079

spring:
  application:
    name: zuul-service
